name: Deploy to IIS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check .NET
      run: dotnet --info

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish -c Release -o publish

    # ✅ Stop IIS App Pool using CMD (no WebAdministration)
    - name: Stop IIS App Pool
      shell: cmd
      run: |
        %windir%\system32\inetsrv\appcmd stop apppool /apppool.name:"backendService"
        timeout /t 3 /nobreak

    - name: Deploy to IIS folder
      shell: powershell
      run: |
        if (Test-Path "C:\inetpub\wwwroot\MDMAAppPublish") {
          Get-ChildItem "C:\inetpub\wwwroot\MDMAAppPublish" -Recurse | Remove-Item -Recurse -Force -ErrorAction SilentlyContinue
        }
        Copy-Item "publish\*" "C:\inetpub\wwwroot\MDMAAppPublish" -Recurse -Force

    # ✅ Start IIS App Pool using CMD (no WebAdministration)
    - name: Start IIS App Pool
      shell: cmd
      run: |
        %windir%\system32\inetsrv\appcmd start apppool /apppool.name:"backendService"
